//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Samples.Kinect.Webserver.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Samples.Kinect.Webserver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized property name.
        /// </summary>
        internal static string PropertyNameUnrecognized {
            get {
                return ResourceManager.GetString("PropertyNameUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property is read-only.
        /// </summary>
        internal static string PropertyReadOnly {
            get {
                return ResourceManager.GetString("PropertyReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating property value.
        /// </summary>
        internal static string PropertySetError {
            get {
                return ResourceManager.GetString("PropertySetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized property value format.
        /// </summary>
        internal static string PropertyValueInvalidFormat {
            get {
                return ResourceManager.GetString("PropertyValueInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported resolution.
        /// </summary>
        internal static string PropertyValueUnsupportedResolution {
            get {
                return ResourceManager.GetString("PropertyValueUnsupportedResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket connection has been abandoned by client.
        /// </summary>
        internal static string SocketClientDisconnectionDetected {
            get {
                return ResourceManager.GetString("SocketClientDisconnectionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client has requested to close socket connection.
        /// </summary>
        internal static string SocketClosedByClient {
            get {
                return ResourceManager.GetString("SocketClosedByClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server has requested to close socket connection.
        /// </summary>
        internal static string SocketClosedByServer {
            get {
                return ResourceManager.GetString("SocketClosedByServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized stream name.
        /// </summary>
        internal static string StreamNameUnrecognized {
            get {
                return ResourceManager.GetString("StreamNameUnrecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported color format.
        /// </summary>
        internal static string UnsupportedColorFormat {
            get {
                return ResourceManager.GetString("UnsupportedColorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported key type for serialization of a dictionary, keys must be strings..
        /// </summary>
        internal static string UnsupportedKeyType {
            get {
                return ResourceManager.GetString("UnsupportedKeyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported sensor stream type.
        /// </summary>
        internal static string UnsupportedStreamType {
            get {
                return ResourceManager.GetString("UnsupportedStreamType", resourceCulture);
            }
        }
    }
}
